#!/usr/bin/env bash
# Archive (2020) — canonical palette + font choices.
# Single source of truth. Change a colour here, every per-app config
# regenerates from it.
#
# When SOURCED: exposes ARCHIVE_* shell variables.
#   source ~/dotfiles/mods/archive-2020/palette.sh
#
# When EXECUTED: dumps a summary, or emits a per-tool format on stdout.
#   ./palette.sh           # human-readable dump
#   ./palette.sh --kitty   # kitty colour-config block
#   ./palette.sh --css     # GTK / Waybar @define-color block
#   ./palette.sh --hyprland # hyprland 0xAARRGGBB border/general values
#   ./palette.sh --env     # KEY=VALUE pairs (for non-bash consumers)

# ── Colours ──────────────────────────────────────────────────────────────────
# Smoke white — everyday foreground (text, borders, chrome)
ARCHIVE_FG="#e8e6e1"
# Dim smoke — inactive text, dividers
ARCHIVE_FG_DIM="#787670"
# Amber — WARNING / ALERT only (battery low, mute, recording, urgent dunst)
ARCHIVE_WARN="#ffb000"
# Surface — primary background
ARCHIVE_BG="#0a0a0a"
# Surface +1 — raised background (notifications, menus, rofi)
ARCHIVE_BG_ALT="#141414"
# Black for inverted-highlight fg (focused workspace pill, selected rofi entry)
ARCHIVE_INVERT_FG="#000000"

# ── Fonts ────────────────────────────────────────────────────────────────────
# Body / terminal / small UI — already installed via dotfiles/install.sh
ARCHIVE_FONT_BODY="JetBrainsMono Nerd Font"
# Display — waybar clock + rofi prompt only. Shipped under fonts/ in this mod.
ARCHIVE_FONT_DISPLAY="Aldrich"

# ── Helpers ──────────────────────────────────────────────────────────────────
# Convert "#rrggbb" → "rr,gg,bb"
hex_to_rgb_csv() {
    local h="${1#'#'}"
    printf "%d,%d,%d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}
# Convert "#rrggbb" → "0xffrrggbb" (Hyprland's AARRGGBB form, alpha = ff)
hex_to_hypr() {
    local h="${1#'#'}"
    printf "0xff%s" "$h"
}

ARCHIVE_FG_RGB=$(hex_to_rgb_csv "$ARCHIVE_FG")
ARCHIVE_FG_DIM_RGB=$(hex_to_rgb_csv "$ARCHIVE_FG_DIM")
ARCHIVE_WARN_RGB=$(hex_to_rgb_csv "$ARCHIVE_WARN")
ARCHIVE_BG_RGB=$(hex_to_rgb_csv "$ARCHIVE_BG")
ARCHIVE_BG_ALT_RGB=$(hex_to_rgb_csv "$ARCHIVE_BG_ALT")

# ── Emit modes (only when executed, not sourced) ─────────────────────────────
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    case "${1:-}" in
        --kitty)
            cat <<EOF
# Archive (2020) palette — generated by palette.sh; do not edit by hand
foreground            $ARCHIVE_FG
background            $ARCHIVE_BG
cursor                $ARCHIVE_FG
cursor_text_color     $ARCHIVE_BG
selection_foreground  $ARCHIVE_BG
selection_background  $ARCHIVE_FG
url_color             $ARCHIVE_FG_DIM

# 16-colour table. Smoke for "normal" slots, amber only for "warning" slots
# (red + yellow indices), dim smoke for blue/magenta. No real reds, greens,
# blues — keeps shell output consistent with the no-chroma rule.
color0   $ARCHIVE_BG
color8   $ARCHIVE_FG_DIM
color1   $ARCHIVE_WARN
color9   $ARCHIVE_WARN
color2   $ARCHIVE_FG
color10  $ARCHIVE_FG
color3   $ARCHIVE_WARN
color11  $ARCHIVE_WARN
color4   $ARCHIVE_FG_DIM
color12  $ARCHIVE_FG_DIM
color5   $ARCHIVE_FG_DIM
color13  $ARCHIVE_FG_DIM
color6   $ARCHIVE_FG_DIM
color14  $ARCHIVE_FG
color7   $ARCHIVE_FG
color15  $ARCHIVE_FG
EOF
            ;;
        --css)
            cat <<EOF
/* Archive (2020) palette — generated by palette.sh; do not edit by hand */
@define-color archive_fg        $ARCHIVE_FG;
@define-color archive_fg_dim    $ARCHIVE_FG_DIM;
@define-color archive_warn      $ARCHIVE_WARN;
@define-color archive_bg        $ARCHIVE_BG;
@define-color archive_bg_alt    $ARCHIVE_BG_ALT;
@define-color archive_invert_fg $ARCHIVE_INVERT_FG;
EOF
            ;;
        --hyprland)
            cat <<EOF
# Archive (2020) palette — generated by palette.sh; do not edit by hand
# Drop-in values for hyprland.conf 'general' / 'decoration' blocks.
\$archive_fg       = $(hex_to_hypr "$ARCHIVE_FG")
\$archive_fg_dim   = $(hex_to_hypr "$ARCHIVE_FG_DIM")
\$archive_warn     = $(hex_to_hypr "$ARCHIVE_WARN")
\$archive_bg       = $(hex_to_hypr "$ARCHIVE_BG")
\$archive_bg_alt   = $(hex_to_hypr "$ARCHIVE_BG_ALT")
EOF
            ;;
        --env)
            for v in ARCHIVE_FG ARCHIVE_FG_DIM ARCHIVE_WARN \
                     ARCHIVE_BG ARCHIVE_BG_ALT ARCHIVE_INVERT_FG \
                     ARCHIVE_FONT_BODY ARCHIVE_FONT_DISPLAY; do
                printf "%s=%s\n" "$v" "${!v}"
            done
            ;;
        ""|--dump|-h|--help)
            printf "Archive (2020) palette\n"
            printf "  ARCHIVE_FG          %s   smoke white (primary fg)\n"      "$ARCHIVE_FG"
            printf "  ARCHIVE_FG_DIM      %s   dim smoke (inactive)\n"          "$ARCHIVE_FG_DIM"
            printf "  ARCHIVE_WARN        %s   amber (warning only)\n"          "$ARCHIVE_WARN"
            printf "  ARCHIVE_BG          %s   surface\n"                       "$ARCHIVE_BG"
            printf "  ARCHIVE_BG_ALT      %s   raised surface\n"                "$ARCHIVE_BG_ALT"
            printf "  ARCHIVE_INVERT_FG   %s   inverted text on smoke bg\n"     "$ARCHIVE_INVERT_FG"
            printf "  ARCHIVE_FONT_BODY     %s\n"                               "$ARCHIVE_FONT_BODY"
            printf "  ARCHIVE_FONT_DISPLAY  %s\n"                               "$ARCHIVE_FONT_DISPLAY"
            printf "\nEmit modes:\n"
            printf "  ./palette.sh --kitty\n"
            printf "  ./palette.sh --css\n"
            printf "  ./palette.sh --hyprland\n"
            printf "  ./palette.sh --env\n"
            ;;
        *)
            printf "unknown mode: %s\n" "$1" >&2
            printf "try: --kitty | --css | --hyprland | --env | --dump\n" >&2
            exit 2
            ;;
    esac
fi
